name: 'JSDoc Action'
description: 'GitHub Action to build JSDoc documentation'
author: 'André Storhaug'
branding:
  icon: 'file-text'  
  color: 'yellow'
inputs:
  source_dir:
    description: 'Source directory to build documentation from'
    required: true
  output_dir:
    description: 'Output folder for the generated documentation'
    default: './out'
  config_file:
    description: 'The path to a JSDoc configuration file'
  template_name:
    description: 'The name of a JSDoc template to install'
  template_dir:
    description: 'The relative location of the template files within the template package'
  front_page:
    description: 'The path to a Markdown file to be used as a the front page'
runs:
  using: 'node12'
  main: 'src/index.js'
